plugins {
    id 'java-library'
    id 'maven-publish'
}

group 'com.eventjournal'
version '0.13.2'

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allSource
    archiveClassifier.set('sources')
}

tasks.register('javadocJar', Jar) {
    from tasks.javadoc
    archiveClassifier.set('javadoc')
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'client'
            artifact tasks.sourcesJar
            artifact tasks.javadocJar
            from components.java
            pom {
                name = 'client'
                description = 'event-journal java sdk'
                url = 'https://github.com/wemojema/event-journal-java-sdk'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'wemojema'
                        name = 'Wemojema'
                        email = 'jeff@wemojema.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/wemojema/event-journal-java-sdk.git'
                    developerConnection = 'scm:git:ssh://github.com/wemojema/event-journal-java-sdk.git'
                    url = 'https://github.com/wemojema/event-journal-java-sdk'
                }
            }
        }
    }
}

dependencies {
    def jacksonVersion = '2.12.5'
    implementation 'org.slf4j:slf4j-api:1.7.22'
    api 'org.reflections:reflections:0.10.2'
    api 'com.fasterxml.jackson.core:jackson-core:' + jacksonVersion
    api 'com.fasterxml.jackson.core:jackson-annotations:' + jacksonVersion
    api 'com.fasterxml.jackson.core:jackson-databind:' + jacksonVersion
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:' + jacksonVersion

    testImplementation 'ch.qos.logback:logback-classic:1.2.3'
    testImplementation 'io.symphonia:lambda-logging:1.0.3'
    testImplementation 'com.github.javafaker:javafaker:1.0.2'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.0'
}

test {
    useJUnitPlatform()
}
